steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-west1-docker.pkg.dev/node-nest-ms-ecoapp/eco-registry-image/client-gw",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-west1-docker.pkg.dev/node-nest-ms-ecoapp/eco-registry-image/client-gw",
      ]
options:
  logging: "CLOUD_LOGGING_ONLY"